[package]
name = "socksns"
version = "0.1.0"
license = "MIT"
authors = ["Steven Engler"]
edition = "2018"
repository = "https://github.com/stevenengler/socksns"
description = "A tool for running an application in an isolated network namespace, with external network access only through a SOCKS proxy."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"
unshare = "0.5.1"
users = "0.11.0"
nix = "0.19.0"
passfd = "0.1.3"
tokio = { version = "0.3.4", features = ["net", "rt", "io-util", "macros", "sync"] }
